apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wolf-street-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /user-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - path: /order-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 8085
          - path: /portfolio-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: portfolio-service
                port:
                  number: 8083
