server:
  port: 8085
  servlet:
    context-path: /order-service
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: 'order-service'
    schema-registry-url: http://schema-registry-service:8081

grpc:
  client:
    portfolio-service:
      address: static://localhost:6565
      enable-keep-alive: true
      negotiation-type: plaintext

security:
  jwt:
    secret_key: dXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3NfdXNhY2hldl9odWVzb3M=

management:
  endpoints:
